# This is NOT to set up the project, but instead to run a Jenkins Server for running a build pipeline

version: "3.9"


services:
  docker_dind:
    privileged: true
    image: docker:dind
    ports:
      - 2376:2376
    volumes: 
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    networks: 
      jenkins:
        aliases:
          - docker
  jenkins:
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    volumes: 
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    environment: 
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks: 
      jenkins:


volumes:
  jenkins-docker-certs:
  jenkins-data:

networks: 
  jenkins: