name: Continuous Integration
on: pull_request

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.102
      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build .Net
        run: dotnet build --configuration Release
      - name: Install NPM packages
        working-directory: ./DotnetTemplate.Web
        run: npm install
      - name: Build Typescript
        working-directory: ./DotnetTemplate.Web
        run: npm run build
      - name: Run .Net Tests
        run: dotnet test
      - name: Run Spec Tests
        working-directory: ./DotnetTemplate.Web
        run: npm t
      - name: Run Linting
        working-directory: ./DotnetTemplate.Web
        run: npm run lint
      